name: ptsa
channels:
- defaults
dependencies:
- cycler=0.10.0=py36_0
- freetype=2.5.5=2
- icu=54.1=0
- libpng=1.6.27=0
- mkl=2017.0.1=0
- numpy=1.12.1=py36_0
- openssl=1.0.2k=2
- pandas=0.20.1=np112py36_0
- pip=9.0.1=py36_1
- pyparsing=2.1.4=py36_0
- python=3.6.1=2
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- pywavelets=0.5.2=np112py36_0
- readline=6.2=2
- scipy=0.19.0=np112py36_0
- setuptools=27.2.0=py36_0
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xarray=0.9.5=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - alabaster==0.7.10
  - babel==2.4.0
  - bleach==2.0.0
  - coverage==4.4.1
  - decorator==4.0.11
  - docutils==0.13.1
  - entrypoints==0.2.2
  - html5lib==0.999999999
  - imagesize==0.7.1
  - ipython-genutils==0.2.0
  - jinja2==2.9.6
  - jsonschema==2.6.0
  - jupyter-core==4.3.0
  - markupsafe==1.0
  - mistune==0.7.4
  - nbconvert==5.2.1
  - nbformat==4.3.0
  - nbsphinx==0.2.13
  - pandocfilters==1.4.1
  - ptsa==1.1.0.dev0
  - py==1.4.33
  - pygments==2.2.0
  - pytest==3.1.0
  - pytest-cov==2.5.1
  - requests==2.14.2
  - snowballstemmer==1.2.1
  - sphinx==1.6.1
  - sphinx-rtd-theme==0.2.4
  - sphinxcontrib-websupport==1.0.1
  - testpath==0.3.1
  - traitlets==4.3.2
  - typing==3.6.1
  - webencodings==0.5.1
